name: Build TAR Release in Docker CI

on: push

env:
  TERM: vt100 
  APP: eco

jobs:

  build-mix:

    runs-on: ubuntu-latest

    env:
      TEST_LOCALLY_AT: /tmp/eco/mix
      ECO_PORT: 1883

    steps:
    - uses: actions/checkout@v2
    - name: Build Release TAR
      run: test/build-in-docker/build-mix.sh
  
