name: Build Docker Release CI

on: push

jobs:

  build-rebar3:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Release Container
      run: test/docker/build-rebar3.sh

  build-distillery:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Release Container
      run: test/docker/build-distillery.sh

  build-mix:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Release Container
      run: test/docker/build-mix.sh
