name: Build Docker Release CI

on: push

env:
  TERM: vt100 

jobs:

  build-rebar3:

    runs-on: ubuntu-latest

    outputs: 
      image: ${{steps.build.outputs.image}} 
    steps:
    - uses: actions/checkout@v2
    - name: Build Release Container
      id: build
      run: test/docker/build-rebar3.sh

  run-rebar3:

    runs-on: ubuntu-latest

    needs: build-rebar3
    steps:
    - name: Running rebar3 Release Container
      run: echo "Docker image ${{needs.build-rebar3.outputs.image}}"

  build-distillery:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Release Container
      run: test/docker/build-distillery.sh

  build-mix:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Release Container
      run: test/docker/build-mix.sh
