name: Build Docker Release CI

on: push

env:
  TERM: vt100 
  APP: eco

jobs:

  build-rebar3:

    runs-on: ubuntu-latest

    env:
      TEST_LOCALLY_AT: /tmp/eco/rebar3
    steps:
    - uses: actions/checkout@v2
    - name: Build Release Container
      run: test/docker/build-rebar3.sh

    - name: Preparing Deploy
      run: mkdir -p /home/runner/.ssh/ && touch /home/runner/.ssh/known_hosts
    - name: Deploying image locally
      env:
        RELEASE_VERSION: ${{env.release_version}}
        RELEASE_STORE: ${{env.release_store}}
      run: ./bin/edeliver deploy release locally --version=$RELEASE_VERSION --verbose
    - name: Running rebar3 Release Container
      run: ${TEST_LOCALLY_AT}/eco/bin/eco console


  build-distillery:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Release Container
      run: test/docker/build-distillery.sh

  build-mix:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Release Container
      run: test/docker/build-mix.sh
